### ISSUE TITLE
Exception thrown in afterAll (and beforeAll) not registered in Example.Exception

### ISSUE THREAD

**Issue by BrainCrumbz** [mattflo/NSpec#88] opened 2015-08-30 11:23 UTC
From a quick check, it seems that when an exception is thrown within `afterAll` hook, the corresponding `Example.Exception` remains null. 
From a first look during a debug session, `Example.AssignProperException()` is invoked **before** `RunAndHandleException(RunAfterAll, nspec, ref Exception)` in `Context.Run()`. Thus `AssignProperException` receives a null `contextException` and it thinks everything's ok, so `Example.Exception` remains null. 

We did not check by debug, but from existing tests in async branch the same thing should behave differently for `beforeAll`. When an exception is thrown in there, the `Example.Exception` should be set.

Is that intended?

**Comment by amirrajan** [comment] 2015-08-31 02:26
I don't think we ever considered exception being thrown in the after block. This is most definitely a bug and will take a look at it next week.

**Comment by BrainCrumbz** [comment] 2015-08-31 14:04
Some more feedback: 
after adding more tests on the async branch, it looks like the *after* hooks (context-level `after` and method-level `after_each`) register exceptions correctly. The *after all* hooks (context-level `afterAll` and method-level `after_all`) instead do not register exceptions.

**Comment by BrainCrumbz** [comment] 2015-08-31 17:49
In the meantime we were having a look at this, I hope that's ok. We extended some tests in [this branch](https://github.com/mattflo/NSpec/tree/exceptions-after-before-all) in order to understand the current state. The ones flagged with `Ignore` are not passing as of now, but I think ideally they should. As you can see, if we got testing right, exceptions thrown in method-level `before_all` seem to be missing as well.

**Comment by amirrajan** [comment] 2015-08-31 18:54
No no, please look :-) the more other people contribute the better.

**Comment by BrainCrumbz** [comment] 2015-08-31 19:18
Ok, when you can, please tell us what you think about it (wrong test Vs wrong implementation).

**Comment by amirrajan** [comment] 2015-08-31 20:38
:+1:

**Comment by BrainCrumbz** [comment] 2015-10-07 01:05
What do you think about this issue, and last findings? (where it says *EDIT: It looks like the reason tests fail is that ...*)

**Comment by amirrajan** [comment] 2015-10-08 16:37
It's definitely a bug, and can be miss leading if an exceptions is thrown. Low priority on my radar. I can look at touch points this weekend if you need some guidance on this.

**Comment by BrainCrumbz** [comment] 2015-10-08 23:15
Yes, I guess this issue can move on at a lower priority. As a background thing, it'd be great if you can share more about touch points and about how exception *flows* through the various points (before all, before, ... after, after all) in a classic sub-context (not for a class-level context, I mean).

With that explanation, we can proceed investigating further. Hope the proposal makes sense!

**Comment by amirrajan** [comment] 2015-10-10 15:16
The best test to look at would be this on: https://github.com/mattflo/NSpec/blob/master/NSpecSpecs/describe_RunningSpecs/Exceptions/describe_expected_exception_in_act.cs

**Comment by BrainCrumbz** [comment] 2015-10-10 15:39
I see, we had to touch that in order to support async. But, isn't that a test on *act*? How does it relate to *after all* case? Tnx

**Comment by BrainCrumbz** [comment] 2015-10-10 15:42
I'd be more interested in understanding what is going on in `Context.Run` [here](https://github.com/mattflo/NSpec/blob/master/NSpec/Domain/Context.cs#L186), especially: how does a thrown Exception flows through the various steps? 

That's because, from what we initially saw, I got the impression that it's like an Exception thrown in an context *after* hook gets somehow lost, either at the end of that same context, or when running up the context hierarchy.

**Comment by amirrajan** [comment] 2015-10-10 23:26
I'm an idiot... wrong test. In this one, an exception is _unintentionally_ thrown and tickles down: https://github.com/mattflo/NSpec/blob/master/NSpecSpecs/describe_RunningSpecs/Exceptions/when_before_contains_exception.cs#L17

**Comment by amirrajan** [comment] 2015-10-10 23:28
Basically all examples fail with an `ExampleFailureException` and the `InnerException` points to what/where it happened.

**Comment by BrainCrumbz** [comment] 2015-10-11 10:43
[wrong referenced issue]

**Comment by BrainCrumbz** [comment] 2015-10-11 13:46
For some reason that does not seem to happen on beforeAll/afterAll hooks: the `InnerException` is not always correct.

We're investigating on this issue at [this branch](https://github.com/mattflo/NSpec/tree/exceptions-after-before-all) and we're adding some tests to focus on it.

If you run e.g. this new `when_before_all_contains_exception.cs` [here](https://github.com/mattflo/NSpec/blob/exceptions-after-before-all/NSpecSpecs/describe_RunningSpecs/Exceptions/when_before_all_contains_exception.cs#L60) (not ignoring it of course) you'll see that the reported inner exception does not come from `beforeAll`, but from `act` hook.

**Comment by BrainCrumbz** [comment] 2015-10-11 14:28
Adding to the previous post, here follows the outcome from investigating on that test:

1. In class context (`SpecClass`), Exception is null
1. In method level context (`method level context`), Exception is `BeforeAllException`
1. In sub-context (`exception thrown by both beforeAll and act`):
  1. the `act` hook runs anyway. Not sure this should happen, or if it should depend on fail-fast, but that's it
  1. sub-context Exception is `ActException`
  1. example Exception gets set to `ActException`, because of `Example.AssignProperException()`

Finally, the test checks on example Exception, and it fails because it finds `ActException` instead of `BeforeAllException`.
Which is the wrong step here?

From what I recall, the same thing should happen also on afterAll hook, so probably solving this *beforeAll* issue would also solve that *afterAll*.

**Comment by amirrajan** [comment] 2015-10-12 18:04
I'll research this weekend. The exception handling is indeed pretty green. The `act` has been given the most attention (primarily because when I was writing tests, most of hell broke loose in there or in the `it`).

**Comment by BrainCrumbz** [comment] 2015-10-13 09:00
Yep, that is completely fair. 
It looks like there's something funny going on when exceptions are thrown *outside of any example*, i.e. before or after the `for (int i = 0; i < Examples.Count; i++)` cycle [here](https://github.com/mattflo/NSpec/blob/8e736ccf943bb670239e90c98f211f2b5a0e3f16/NSpec/Domain/Context.cs#L197). As you rightly say, it is a matter of how it should behave.

Our 2 cents: 
* *beforeAll* should likely behave as *before*. So e.g. if an exception in *before* in a context prevents any example in that context from running, the same should happen for an exception in *beforeAll*. If the exception in *before* is the reported one (and not a subsequent exception in exampl), again the same should be for the exception in *beforeAll*.
* at first thought, along the same path, *afterAll* should behave as *after*. If there's an exception in any of those two, I guess one would like to see that reported, even if the example itseld ran correctly. It means anyway that there's something wrong in her/his test code.

**Comment by amirrajan** [comment] 2015-10-13 22:03
That sounds perfect. A failure in any of the setup should constitute a failure for all sub context and examples.

**Comment by amirrajan** [comment] 2015-10-13 22:04
The tricky part is how do you communicate/report where the failure occurred (specifically in the `after` and `afterAll`).

**Comment by BrainCrumbz** [comment] 2015-10-13 22:47
Ok, I'll also think about that. On the other extreme of *the path*, we should find a way to not run any example and report failure together with each example, when exception occurs in `beforeAll`.

**Comment by amirrajan** [comment] 2015-10-14 19:36
That would be extremely cool if we could do that.

**Comment by BrainCrumbz** [comment] 2015-10-17 15:28
While looking at this issue, I think we've also found something strange in `Context` hooks: it looks like `RunBeforeAll` and `RunAfterAll` do not walk up through the context ancestors, as `RunBefores`, `RunAfters` and `RunActs` do instead. In the formers, there's no `RecurseAncestors` call.

If I have a `beforeAll` on a context, and then another `beforeAll` set on a sub-context, shouldn't both be executed when running the sub-context?

**Comment by amirrajan** [comment] 2015-10-17 20:07
Best explanation I have so far is this: https://github.com/mattflo/NSpec/wiki/Execution-Orders

I may have a sample of multiple `beforeAlls` in my smoke tests. I'll get that to you asap.

**Comment by BrainCrumbz** [comment] 2015-10-18 18:24
Ok, my bad then. BeforeAll is supposed to run **once**, not once for each example. So, if a BeforeAll is met in a nested context, only *that* hook should run: any existing ancestor has ran already.

**Comment by amirrajan** [comment] 2015-10-18 18:42
:+1:

**Comment by BrainCrumbz** [comment] 2015-11-02 09:49
An update: after some trials, it seems that the best way to approach this issue is some kind of *2-phases run*:

 1. in first phase, all contexts and examples are run basically as it happens now. The big difference is that proper exception is **not** assigned to any Example. Instead, thrown exceptions are recorded separately for `BeforeAll`, `AfterAll`, the `Example`, and the group made of `Before + Act + After`.

 2. in second phase, all contexts and examples are traversed again only in order to assign the proper exception. Now, in this new phase, exceptions due to `BeforeAll`/ `AfterAll` affect each nested context and example, so they are passed down the chain as inherithed exceptions. At this point you can reason about the proper *exception priority* among `BeforeAll > (Before + Act + Example + After) > AfterAll`.

You can have a look at current incarnation in [exceptions-after-before-all branch](https://github.com/mattflo/NSpec/tree/exceptions-after-before-all), in particular at: 

* [ContextCollection.Run](https://github.com/mattflo/NSpec/blob/348ff9733962ef953bc68b989257fde84f868678/NSpec/Domain/ContextCollection.cs#L37), now invoking `Run` and then `AssignExceptions` on each context
* [Context.Run](https://github.com/mattflo/NSpec/blob/348ff9733962ef953bc68b989257fde84f868678/NSpec/Domain/Context.cs#L186), now recording a `ExceptionBeforeAll` and `ExceptionAfterAll`
* [Context.Exercise](https://github.com/mattflo/NSpec/blob/348ff9733962ef953bc68b989257fde84f868678/NSpec/Domain/Context.cs#L274), now *not* assigning any exception
* [Context.AssignExceptions](https://github.com/mattflo/NSpec/blob/348ff9733962ef953bc68b989257fde84f868678/NSpec/Domain/Context.cs#L224), the new method actually representing the 2nd phase

The split seemed the best way to handle the fact that when an example is run, even up to its related `After` ancestor chain, you might still have some `AfterAll` waiting to be ran afterward. So you only know about *all* thrown exceptions when the outermost `AfterAll` ran, and only by then you have all info needed to assign proper exception to examples.

Now, this is all shiny and great, old and new tests on exceptions are passing ... apart from one *small* issue: `expect<T>`.  
This messes up the whole thing, as in 1st phase it happens that `expect` basically deletes a thrown (expected) exception, then in 2nd phase nobody remembers about that and the same or another exception gets assigned anyway.

So now we're looking for the best way to either record `expect` outcome and apply that in 2nd phase, or maybe to detect `expect` examples and bypass them in 1st phase, to run those in 2nd phase. 

Any suggestions on those or further approaches is more than welcome!

**Comment by amirrajan** [comment] 2015-11-03 16:45
As a first cut, maybe just say that `expect<T>` isn't supported for async? I (personally) don't use `expect` too much. Here is an example: https://github.com/amirrajan/Oak/blob/master/Oak.Tests/describe_DynamicDb/helpful_errors.cs

And this is also an interesting approach to dealing with exceptions:

https://github.com/mattflo/NSpec/issues/59

**Comment by BrainCrumbz** [comment] 2015-11-03 21:40
I'll have a look at those references, but just to be clear: this current issue is both about sync and async. Actually, beside the title, it is also both about afterAll and beforeAll. 
Il 03/Nov/2015 17:45, Amir Rajan <notifications@github.com> ha scritto:As a first cut, maybe just say that expect<T> isn't supported for async? I (personally) don't use expect too much. Here is an example: https://github.com/amirrajan/Oak/blob/master/Oak.Tests/describe_DynamicDb/helpful_errors.cs

And this is also an interesting approach to dealing with exceptions:

#59

**Comment by BrainCrumbz** [comment] 2015-11-03 21:43
So at the moment, current library on main branch does not reports exceptions correctly when thrown in afterAll, afterAllAsync, beforeAll, beforeAllAsync
Il 03/Nov/2015 22:40, BrainCrumbz Admin <admin@braincrumbz.com> ha scritto:I'll have a look at those references, but just to be clear: this current issue is both about sync and async. Actually, beside the title, it is also both about afterAll and beforeAll. 
Il 03/Nov/2015 17:45, Amir Rajan <notifications@github.com> ha scritto:As a first cut, maybe just say that expect<T> isn't supported for async? I (personally) don't use expect too much. Here is an example: https://github.com/amirrajan/Oak/blob/master/Oak.Tests/describe_DynamicDb/helpful_errors.cs

And this is also an interesting approach to dealing with exceptions:

#59

**Comment by amirrajan** [comment] 2015-11-05 03:48
Ah, thanks for the clarification

**Comment by BrainCrumbz** [comment] 2015-11-05 11:01
Regarding expected exceptions, in the end we opted for this approach: 

In first phase, `expect<>` example does not actually clear expected `Context.Exception`. Instead, the clear *intention* is recorded in a boolean. If subsequent exception `after`s throws, the clear intention is reset, so not to hide it.

In second phase, while assigning proper exception to examples, the `Context.Exception` is ignored if clear intention was recorded.

**Comment by amirrajan** [comment] 2015-11-11 17:47
not sure if it's related to this issue (or what I just merged into master), but `describe_context_stack_trace` under `describe_output` is failing right now. Looks like that `act` doesn't retain the exception anymore.

**Comment by BrainCrumbz** [comment] 2015-11-12 08:56
That might as well be, because a number of those `describe_output` tests always failed on our PCs, since the very beginning, so that could have hidden a *new* test fail.

On the other hand, there's a bunch of new tests right on exceptions being detected or not. We'll have a look at this, hoping that the *old* test failures do not hide this new one.

**Comment by amirrajan** [comment] 2015-11-12 18:46
The recent changes I made to `describe_output` removes the explicit execution of the tests via the exe, so it should work on all computers (and os's). 

Still working through getting on this working on mono, and then I'll redo the website and deploy the new version of the package that includes your exception related changes.

**Comment by amirrajan** [comment] 2015-11-12 19:27
`describe_context_stack_trace_output` in `describe_output` is the test that's failing. Pretty sure it's a legitimate failure. Just a heads up (I'll try to get this fixed asap if you can't get to it).

**Comment by amirrajan** [comment] 2015-11-12 23:22
okay, I've just tested it on windows and there is one test that's failing (and I'm pretty sure it's a legitimate failure): 

```
Errors and Failures:
1) Test Failure : NSpecSpecs.describe_output.output_verification(SampleSpecs.Bug.describe_context_stack_trace_output,System.Type[],"")
     Expected string length 370 but was 317. Strings differ at index 78.
  Expected: "...in act\n    is true - FAILED - Context Failure: Exception i..."
  But was:  "...in act\n    is true - FAILED - Expected: True, But was: Fal..."
  ---------------------------------------------^
```

**Comment by BrainCrumbz** [comment] 2015-11-13 08:53
Ran on Windows (10 64bit w/ Italian language pack). Always getting 4 reds, the same number as from the beginning. Not sure now whether they are **the same** failures or not. Here are the details, the last is the one you mentioned:

**1**
```
Test Name:	output_verification(describe_changing_failure_exception_output,System.Type[],"")
Test FullName:	NSpecSpecs.describe_output.output_verification(describe_changing_failure_exception_output,System.Type[],"")
Test Source:	d:\WS\NET\NSpec framework\NSpec\src\NSpecSpecs\describe_output.cs : line 76
Test Outcome:	Failed
Test Duration:	0:00:00,004

Result Message:	
Expected string length 432 but was 629. Strings differ at index 400.
  Expected: "...e detailed exception message.\n\n1 Examples, 1 Failed, 0 Pen..."
  But was:  "...e detailed exception message.\n   in describe_changing_fail..."
  ---------------------------------------------^
Result StackTrace:	
in NSpec.AssertionExtensions.should_be(String actual, String expected) in d:\WS\NET\NSpec framework\NSpec\src\NSpec\AssertionExtensions.cs:riga 80
in NSpecSpecs.describe_output.output_verification(Type output, Type[] testClasses, String tags) in d:\WS\NET\NSpec framework\NSpec\src\NSpecSpecs\describe_output.cs:riga 89
```

**2**
```
Test Name:	output_verification(describe_changing_stacktrace_message_output,System.Type[],"")
Test FullName:	NSpecSpecs.describe_output.output_verification(describe_changing_stacktrace_message_output,System.Type[],"")
Test Source:	d:\WS\NET\NSpec framework\NSpec\src\NSpecSpecs\describe_output.cs : line 76
Test Outcome:	Failed
Test Duration:	0:00:00,038

Result Message:	
Expected string length 442 but was 641. Strings differ at index 370.
  Expected: "...tion.\nAn exception was thrown\nMore Information to help dia..."
  But was:  "...tion.\nAn exception was thrown\n   in describe_changing_stac..."
  ----------------------------------------------^
Result StackTrace:	
in NSpec.AssertionExtensions.should_be(String actual, String expected) in d:\WS\NET\NSpec framework\NSpec\src\NSpec\AssertionExtensions.cs:riga 80
in NSpecSpecs.describe_output.output_verification(Type output, Type[] testClasses, String tags) in d:\WS\NET\NSpec framework\NSpec\src\NSpecSpecs\describe_output.cs:riga 89
```

**3**
```
Test Name:	output_verification(describe_specifications_output,System.Type[],"")
Test FullName:	NSpecSpecs.describe_output.output_verification(describe_specifications_output,System.Type[],"")
Test Source:	d:\WS\NET\NSpec framework\NSpec\src\NSpecSpecs\describe_output.cs : line 76
Test Outcome:	Failed
Test Duration:	0:00:00,015

Result Message:	
Expected string length 1237 but was 2041. Strings differ at index 713.
  Expected: "...xpected: False, But was: True\n\nnspec. describe specificati..."
  But was:  "...xpected: False, But was: True\n   in describe_specification..."
  ---------------------------------------------^
Result StackTrace:	
in NSpec.AssertionExtensions.should_be(String actual, String expected) in d:\WS\NET\NSpec framework\NSpec\src\NSpec\AssertionExtensions.cs:riga 80
in NSpecSpecs.describe_output.output_verification(Type output, Type[] testClasses, String tags) in d:\WS\NET\NSpec framework\NSpec\src\NSpecSpecs\describe_output.cs:riga 89
```

**4**
```
Test Name:	output_verification(SampleSpecs.Bug.describe_context_stack_trace_output,System.Type[],"")
Test FullName:	NSpecSpecs.describe_output.output_verification(SampleSpecs.Bug.describe_context_stack_trace_output,System.Type[],"")
Test Source:	d:\WS\NET\NSpec framework\NSpec\src\NSpecSpecs\describe_output.cs : line 76
Test Outcome:	Failed
Test Duration:	0:00:00,004

Result Message:	
Expected string length 370 but was 688. Strings differ at index 78.
  Expected: "...in act\n    is true - FAILED - Context Failure: Exception i..."
  But was:  "...in act\n    is true - FAILED - Expected: True, But was: Fal..."
  ---------------------------------------------^
Result StackTrace:	
in NSpec.AssertionExtensions.should_be(String actual, String expected) in d:\WS\NET\NSpec framework\NSpec\src\NSpec\AssertionExtensions.cs:riga 80
in NSpecSpecs.describe_output.output_verification(Type output, Type[] testClasses, String tags) in d:\WS\NET\NSpec framework\NSpec\src\NSpecSpecs\describe_output.cs:riga 89
```

**Comment by BrainCrumbz** [comment] 2015-11-13 09:53
Restricting on the last failing test, the 2 texts being compared are:

**expected**
```
describe context stack trace
  exception thrown in act
    is true - FAILED - Context Failure: Exception in act., Example Failure: Expected: True, But was: False

**** FAILURES ****

nspec. describe context stack trace. exception thrown in act. is true.
Context Failure: Exception in act., Example Failure: Expected: True, But was: False

1 Examples, 1 Failed, 0 Pending
```

**actual**
```
describe context stack trace
  exception thrown in act
    is true - FAILED - Expected: True, But was: False

**** FAILURES ****

nspec. describe context stack trace. exception thrown in act. is true.
Context Failure: Exception in act., Example Failure: Expected: True, But was: False
   in SampleSpecs.Bug.describe_context_stack_trace.MethodThrowsExceptionAndShouldBeInStackTrace() in d:\WS\NET\NSpec framework\NSpec\src\SampleSpecs\Bug\describe_context_stack_trace.cs:riga 24
   in SampleSpecs.Bug.describe_context_stack_trace.<exception_thrown_in_act>b__0() in d:\WS\NET\NSpec framework\NSpec\src\SampleSpecs\Bug\describe_context_stack_trace.cs:riga 14

1 Examples, 1 Failed, 0 Pending
```

So, now, I'd like to put up an actual failing test on exceptions, not related to *describe_output*, where the act exception is not reported.

On a side note: the stack-trace is still there even after scrubbing, and in the end on our machine the test will fail anyway. That's because for some reason on our machines stack-trace lines start with `in SampleSpecs.Bug...`, instead of `at SampleSpecs.Bug...`. I guess it's because of OS language.

**Comment by BrainCrumbz** [comment] 2015-11-13 10:21
Please have a look at [bug/describe_context_stack_trace_output branch](https://github.com/mattflo/NSpec/tree/bug/describe_context_stack_trace_output). 

The newly added unit test, `more_when_act_contains_exception`, has its `SpecClass` copied over from `SampleSpecs.Bug.describe_context_stack_trace`. And still, its testcases are passing. 

When I debug and peek inside the running example, I see:

example.Context
```
{exception thrown in act, L2, 1 exm, 0 ctx, InvalidOperationException}
    [NSpec.Domain.MethodContext]: {exception thrown in act, L2, 1 exm, 0 ctx, InvalidOperationException}
    Act: {Method = {Void <exception_thrown_in_act>b__0()}}
    ...
    Exception: {"Exception in act."}
    ...
    Name: "exception thrown in act"
    ...
```

example.Exception:
```
{"Context Failure: Exception in act., Example Failure:   Expected: True\r\n  But was:  False\r\n"}
    [NSpec.Domain.ExampleFailureException]: {"Context Failure: Exception in act., Example Failure:   Expected: True\r\n  But was:  False\r\n"}
    ...
    InnerException: {"Exception in act."}
    Message: "Context Failure: Exception in act., Example Failure:   Expected: True\r\n  But was:  False\r\n"
    ...
```

**Comment by amirrajan** [comment] 2015-11-13 15:26
I think the italian language pack is the key.

Try updating [this line](https://github.com/mattflo/NSpec/blob/bug/describe_context_stack_trace_output/NSpecSpecs/describe_output.cs#L104) to:

    return String.Join("\n", 
      s.Split('\n')
        .Where(a => !a.Trim().StartsWith("in"))
        .Where(a => !a.Trim().StartsWith("at"))).Replace("\r", "");

**Comment by BrainCrumbz** [comment] 2015-11-13 16:06
Yep, that of course did the trick. Sure, the main cause of test failing is still there. But I don't get how behaviour seems to be different between `describe_output` test and `more_when_act_contains_exception`

**Comment by amirrajan** [comment] 2015-11-13 17:13
I'll take a look this weekend, see if I can create a test that isn't reliant on anything inside of `describe_output`, and look at `more_when_act_contains_exception`. Just haven't had a chance to thoroughly look at this yet.

**Comment by BrainCrumbz** [comment] 2015-11-23 10:23
Hi. Any luck with finding the root cause of this?

**Comment by amirrajan** [comment] 2015-11-29 03:39
Turkey coma. Will look at this tomorrow XD

**Comment by amirrajan** [comment] 2015-11-29 19:29
Here's the output for the tests (actual and expected from previous version). It's minor from the looks of it. I think it's okay, what do you think

```
ACTUAL:

describe context stack trace
  exception thrown in act
    is true - FAILED - Expected: True, But was: False

**** FAILURES ****

nspec. describe context stack trace. exception thrown in act. is true.
Context Failure: Exception in act., Example Failure: Expected: True, But was: False

1 Examples, 1 Failed, 0 Pending



EXPECTED:

describe context stack trace
  exception thrown in act
    is true - FAILED - Context Failure: Exception in act., Example Failure: Expected: True, But was: False

**** FAILURES ****

nspec. describe context stack trace. exception thrown in act. is true.
Context Failure: Exception in act., Example Failure: Expected: True, But was: False

1 Examples, 1 Failed, 0 Pending
```

**Comment by amirrajan** [comment] 2015-11-29 19:30
The regression is on line 3 where the original was

```is true - FAILED - Context Failure: Exception in act., Example Failure: Expected: True, But was: False````

But the new version is:

```is true - FAILED - Expected: True, But was: False```

I think it's minor and I can update the test so that the test passes with the new output.

**Comment by BrainCrumbz** [comment] 2015-11-30 08:59
Thanks for the inspection. I haven't checked the code again, but why the output is different in the first place? It looks like the original version shows a more informative message, it is a little bit of a pity to loose that.

Do you know/ remember where/how that output is generated? I can have a look into this before deciding to update the test to the new output.

**Comment by amirrajan** [comment] 2015-11-30 21:26
Let me see if I can do a bisect and figure out when this regression occurred. It'll be this weekend though.

**Comment by amirrajan** [comment] 2015-12-07 13:34
I'm gonna go ahead and deploy. This is a minor regression (we'll see if anyone complains).

**Closed by amirrajan** 2015-12-07 13:34 UTC

**Comment by BrainCrumbz** [comment] 2015-12-07 14:47
:+1:

**Comment by amirrajan** [comment] 2015-12-14 01:45
published in 1.0.4. success!

still need to redo website generation (working in `gh-pages-rewrite`)

**Comment by BrainCrumbz** [comment] 2015-12-14 09:13
Thanks for info!

**Comment by amirrajan** [comment] 2015-12-14 17:34
Thank for your help!!
